==========================================
SLURM_CLUSTER_NAME = paramganga
SLURM_ARRAY_JOB_ID = 
SLURM_ARRAY_TASK_ID = 
SLURM_ARRAY_TASK_COUNT = 
SLURM_ARRAY_TASK_MAX = 
SLURM_ARRAY_TASK_MIN = 
SLURM_JOB_ACCOUNT = iitr
SLURM_JOB_ID = 120534
SLURM_JOB_NAME = betavae
SLURM_JOB_NODELIST = gpu005
SLURM_JOB_USER = angetkar_mk.iitr
SLURM_JOB_UID = 38418
SLURM_JOB_PARTITION = gpu
SLURM_TASK_PID = 12606
SLURM_SUBMIT_DIR = /home/angetkar_mk.iitr/Mrunmay/PyTorch-VAE
SLURM_CPUS_ON_NODE = 10
SLURM_NTASKS = 10
SLURM_TASK_PID = 12606
==========================================
no change     /home/apps/DL/DL-CondaPy3.7/condabin/conda
no change     /home/apps/DL/DL-CondaPy3.7/bin/conda
no change     /home/apps/DL/DL-CondaPy3.7/bin/conda-env
no change     /home/apps/DL/DL-CondaPy3.7/bin/activate
no change     /home/apps/DL/DL-CondaPy3.7/bin/deactivate
no change     /home/apps/DL/DL-CondaPy3.7/etc/profile.d/conda.sh
no change     /home/apps/DL/DL-CondaPy3.7/etc/fish/conf.d/conda.fish
no change     /home/apps/DL/DL-CondaPy3.7/shell/condabin/Conda.psm1
no change     /home/apps/DL/DL-CondaPy3.7/shell/condabin/conda-hook.ps1
no change     /home/apps/DL/DL-CondaPy3.7/lib/python3.7/site-packages/xontrib/conda.xsh
no change     /home/apps/DL/DL-CondaPy3.7/etc/profile.d/conda.csh
no change     /home/angetkar_mk.iitr/.bashrc
No action taken.
Global seed set to 1265
Missing logger folder: logs/BetaVAE
Traceback (most recent call last):
  File "/home/angetkar_mk.iitr/Mrunmay/PyTorch-VAE/run.py", line 45, in <module>
    runner = Trainer(logger=tb_logger,
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/angetkar_mk.iitr/.conda/envs/betavae/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 38, in insert_env_defaults
    return fn(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/angetkar_mk.iitr/.conda/envs/betavae/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 426, in __init__
    gpu_ids, tpu_cores = self._parse_devices(gpus, auto_select_gpus, tpu_cores)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/angetkar_mk.iitr/.conda/envs/betavae/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 1538, in _parse_devices
    gpu_ids = device_parser.parse_gpu_ids(gpus)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/angetkar_mk.iitr/.conda/envs/betavae/lib/python3.11/site-packages/pytorch_lightning/utilities/device_parser.py", line 89, in parse_gpu_ids
    return _sanitize_gpu_ids(gpus)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/angetkar_mk.iitr/.conda/envs/betavae/lib/python3.11/site-packages/pytorch_lightning/utilities/device_parser.py", line 151, in _sanitize_gpu_ids
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: You requested GPUs: [1]
 But your machine only has: [0]
